language: node_js
node_js:
  - node
  - "5"
  - "4"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
sudo: false
branches:
only:
  - master
script: npm test
notifications:
  slack: vulgardisplayofpower:RQzt5qlhpuN4caO9OavVbmoi
